### ISSUE TITLE
The codes of the other methods

### ISSUE THREAD

**Issue by JunMa11** [hbatagelo/laplacianseg#1]
Dear @hbatagelo ,

Thanks for the great demo code.

Would it be possible for you to make the codes of the other compared methods publicly available?

![image](https://user-images.githubusercontent.com/19947331/75005265-d6034980-54a8-11ea-97f7-9ea4a113c03a.png)

Best regards,
Jun

**Comment by hbatagelo** [comment]
Hi Jun,

We are glad that you find our demo code useful.

We cannot distribute the code of the other methods due to third-party licensing terms. Please refer to the web pages of the corresponding authors.

Best,

Harlen

**Comment by JunMa11** [comment]
Thanks for your reply.
