### ISSUE TITLE
How to mark image in Matlab version?

### ISSUE THREAD

**Issue by newjavaer** [hbatagelo/laplacianseg#2]
How to mark image in Matlab version?

**Comment by newjavaer** [comment]
And how to use qmake tool to run the .exe in C++ version?

**Comment by hbatagelo** [comment]
Run `main_interactive('sample_image.png')`, where `sample_image.png` is the image you want to segment. An interactive window will pop open. Click on the image to mark the seed points, then press `c` to connect them. This will create a green foreground label. Now click on the green square in the toolbar and choose a different color (e.g. red). Mark the seed points again, press `c` to create the background label, then press Escape to start the segmentation.

To build the C++ version, simply run `qmake` in the directory where `lcseg.pro` is located, or open the project in Qt Creator and build it from there. Make sure to have Eigen3 and OpenCV 3.4 libraries and headers installed. You can change the project file to adjust the libraries paths, if needed.

**Comment by newjavaer** [comment]
Hi,Sorry to bother you again.
win32: { INCLUDEPATH += "E:\\opencv3\\build\\include" # Note: update with the correct OpenCV include path INCLUDEPATH += "E:\\eigen-3.3.9" OPENCV_LIB_PATH = "E:\\opencv3\\build\\x64\\vc14\\lib" # Note: update with the correct OpenCV lib path 
I have changed the path,but there are still some erro:

Hope for your help.Thank you very much.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hbatagelo/laplacianseg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月7日(星期六) 凌晨0:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hbatagelo/laplacianseg] How to mark image in Matlab version? (#2)





 
Run main_interactive('sample_image.png'), where sample_image.png is the image you want to segment. An interactive window will pop open. Click on the image to mark the seed points, then press c to connect them. This will create a green foreground label. Now click on the green square in the toolbar and choose a different color (e.g. red). Mark the seed points again, press c to create the background label, then press Escape to start the segmentation.
 
To build the C++ version, simply run qmake in the directory where lcseg.pro is located, or open the project in Qt Creator and build it from there. Make sure to have Eigen3 and OpenCV 3.4 libraries and headers installed. You can change the project file to adjust the libraries paths, if needed.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hbatagelo** [comment]
Hi @newjavaer. I'm afraid I won't be able to help you since I haven't tested on Windows. The implementation doesn't use platform-specific libraries, so it should work on Windows (in theory, at least). I guess these problems are related to setting up the dependencies or the compiler.

**Comment by newjavaer** [comment]
Ok,Thank you very much.Can you tell me the average running time of the LC method in the MSRC dataset？I'll use it as a reference.Thank you again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hbatagelo/laplacianseg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 上午7:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hbatagelo/laplacianseg] How to mark image in Matlab version? (#2)





 
Hi @newjavaer. I'm afraid I won't be able to help you since I haven't tested on Windows. The implementation doesn't use platform-specific libraries, so it should work on Windows (in theory, at least). I guess these problems are related to setting up the dependencies or the compiler.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hbatagelo** [comment]
Sorry, I don't have these results readily available. I'd recommend that you run your own timing tests using the provided code.
