### ISSUE TITLE
MATLAB version SPLCH SPLC LCH

### ISSUE THREAD

**Issue by newjavaer** [hbatagelo/laplacianseg#3]
Hi,Is there MATLAB version for SPLCH SPLC LCH?

**Comment by newjavaer** [comment]
QT += concurrent
CONFIG += c++17 console
CONFIG -= app_bundle

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

SOURCES += \
        color.cpp \
        commandlineparser.cpp \
        main.cpp \
        seededsegmentationhard.cpp \
        seededsegmentationsoft.cpp \
        seededspsegmentation.cpp \
        slic.cpp

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

HEADERS += \
    color.h \
    commandlineparser.h \
    seededsegmentationhard.h \
    seededsegmentationsoft.h \
    seededspsegmentation.h \
    slic.h \
    util.h

INCLUDEPATH += D:\eigen
RESOURCES +=

win32: {
INCLUDEPATH += "D:\\opencv3\\build\\include" # Note: update with the correct OpenCV include path
OPENCV_LIB_PATH = "D:\\opencv3\\build\\x64\\vc14\\lib" # Note: update with the correct OpenCV lib path

    debug: {
        LIBS += -L$$OPENCV_LIB_PATH \
                -lopencv_core340d \
                -lopencv_imgproc340d
    }

    release: {
        LIBS += -L$$OPENCV_LIB_PATH \
                -lopencv_core340d \
                -lopencv_imgproc340d
    }
}

#unix: !macx {
#INCLUDEPATH += /usr/include/suitesparse
#LIBS += -lcholmod
#QT_CONFIG -= no-pkg-config
#CONFIG += link_pkgconfig
#PKGCONFIG += opencv eigen3
#}

#unix: macx{
#INCLUDEPATH += /usr/local/include
#INCLUDEPATH += /usr/local/include/eigen3
#LIBS        += -L/usr/local/lib \
#               -lopencv_world \
#               -lspqr -lumfpack -lcholmod -lmetis -lcolamd -lccolamd -lcamd -lamd -lm -lsuitesparseconfig
#}

**Comment by newjavaer** [comment]
And,is there some erro in my lcseg.pro?

**Comment by hbatagelo** [comment]
We don't have an implementation of SPLCH/SPLC/LCH in MATLAB, but we cleaned up the C++ code and migrated the build system to CMake. Hopefully this helps setting up the dependencies.
